### ISSUE TITLE
Getting error String

### ISSUE THREAD

**Issue by tsangaris** [adamwaite/Validator#101]
Hi,

First of all, thanks for this great library! It's really helpful!

I am trying to validate an email using the following code:

    let emailRule = ValidationRulePattern(pattern: EmailValidationPattern.standard, error: ValidationError(message: "wrong type of email") )

    let emailValidationResults = emailValue.validate(rule: emailRule)
        
    switch emailValidationResults {
    case .valid:
        print("everything checks out")
    case .invalid(let someError): 
        print(someError.first?.message)
    }

The ValidationError is as below:

    struct ValidationError: Error {
    
        public let message: String
    
        public init(message m: String) {
            message = m
        }
    }

There are 2 issues:

- If i run the code above the XCode will throw an error saying:

    `"Value of type 'Error' has no member 'message'"`

- If I just use **print(someError.first ?? "")** then i get this: 

    `ValidationError(message: "wrong type of email")`

How do i just get the string "wrong type of email" instead?
Also, why isnt the way i discribed first (someError.first?.message) not working? This is what you say in your documentation as well.

Thank you in advance!

**Comment by adamwaite** [comment]
Hi @tsangaris.

Thanks for the well-formed question.

Looks like the documentation is out-dated! Thank you for pointing that out.

I think in previous versions the `ValidationResult.invalid([Error])` was actually `ValidationResult.invalid([ValidationError])`.

Here I have 2 fixes in mind for you:

1. Cast to `ValidationError` in the switch:
 
```
switch emailValidationResults {
case .valid:
    print("everything checks out")
case .invalid(let someError as [ValidationError]): 
    print(someError.first?.message)
}
```

Or, extend error to have the message property:

```
extension Error {
    
    var message: String {
        return localizedDescription
    }
}
```

So it will use your custom message if it's a `ValidationError`, or fall back to `localizedDescription` on anything else.

To be honest, I don't like the `ValidationError` type, and will probably remove it in the next version, which I plan to write very soon.

Thank you!

**Comment by adamwaite** [comment]
(Re-opening because I need to update the docs)

**Comment by tsangaris** [comment]
Thanks a lot for your response, Adam!

Looking forward to checking the next version. And thanks for helping us not re-inventing the wheel all over again! :)

**Comment by adamwaite** [comment]
Updated the README now 👍
