### ISSUE TITLE
Validate whether a textfield string is an integer

### ISSUE THREAD

**Issue by RowanG1** [adamwaite/Validator#102]
I have tried doing the following:
--------------------
var postalCodeRules = ValidationRuleSet<Int>()    
let minLengthRule = ValidationRuleLength(min: 1, error: ValidationErrors.minLengthInvalid)
postalCodeRules.add(rule: minLengthRule)
--------------------

But I get error in Xcode "Generic parameter type R could not be inferred".

**Comment by adamwaite** [comment]
Hi. You need to specialise the ValidationRuleSet.

Like this:

<img width="1201" alt="screenshot 2018-09-26 at 07 11 31" src="https://user-images.githubusercontent.com/1426233/46060512-89a0c680-c15b-11e8-877b-0c70c11b961c.png">
