### ISSUE TITLE
Xcode 9.4.1 / swift 4.1 build failures

### ISSUE THREAD

**Issue by syvertsj** [adamwaite/Validator#104]
I notice updates here for swift 4.1. Either 'pod' is not pulling it or they are not working.

UISlider, UITextField, UITextView extensions do not conform to ValidatableInterfaceElement.
This can be worked around by unlocking the pod and modifying the extensions.

**Comment by adamwaite** [comment]
Hi. I thought this one was fixed a while ago (https://github.com/adamwaite/Validator/issues/98) - are you sure you are up to date.

In other news, 3.1 was released (Swift 4.2, Xcode 10), so get on that instead. 

https://github.com/adamwaite/Validator/issues/105

**Comment by syvertsj** [comment]
I am using Xcode 9.4.1 at the moment.
I am going to try Xcode 10.
