### ISSUE TITLE
iOS 10 deployment target required?

### ISSUE THREAD

**Issue by metabren** [adamwaite/Validator#106]
Hey @adamwaite! Firstly, thank you for the great library 🙏

I  have a question regarding the deployment target: it was recently raised to 10.0 — was this required to facilitate some new functionality or would you still be able to support 9.1?

Thank you!

**Comment by adamwaite** [comment]
To be honest I just bumped it because I thought < iOS10 is pretty ancient these days. Feel free to open a PR.

**Comment by metabren** [comment]
Thanks @adamwaite. Please see #108.
