### ISSUE TITLE
UITextView+Validator - needs update on notification names

### ISSUE THREAD

**Issue by josipbernat** [adamwaite/Validator#107]
I've created new project using Xcode 10 and Swift 4.2. After installing Validator using CocoaPods I was getting following error: 'UITextViewTextDidChange' has been renamed to 'UITextView.textDidChangeNotification'.

After changing to: UITextView.textDidChangeNotification error was gone. 
I can submit PR with this fix if you want.

Thanks,
Josip

**Comment by adamwaite** [comment]
I think you have an old version of the pod? https://github.com/adamwaite/Validator/blob/master/Validator/Sources/UIKit%2BValidator/UITextView%2BValidator.swift

**Comment by josipbernat** [comment]
I guess you are right! I copy pasted pod 'Validator' into pod file but I didn't make pod update after that.
