### ISSUE TITLE
Xcode 10 build failure - location of textDidChangeNotification() in UITextView+Validator.swift

### ISSUE THREAD

**Issue by syvertsj** [adamwaite/Validator#109]

**Comment by zezek** [comment]
I'm seeing the same thing: 'textDidChangeNotification' has been renamed to 'NSNotification.Name.UITextViewTextDidChange'

**Comment by adamwaite** [comment]
I think you're using an old version. See https://github.com/adamwaite/Validator/issues/107.

**Comment by adamwaite** [comment]
Pod `3.1.1`

**Comment by syvertsj** [comment]
I see this with pod 3.1.1 and 3.1.0.
Version 3.0.2 is alright.

**Comment by adamwaite** [comment]
I can build, run and test on Xcode 10 fine with 3.1.1.

**Comment by drdaz** [comment]
Yeah I'm getting this with Xcode 10 too in one of my projects. Through CocoaPods.

It's very weird though. I tried to create a reproducer with just Validator in the Podfile, but the error doesn't occur.

**Comment by aodhol** [comment]
I get this issue with 3.1.1

**Comment by aodhol** [comment]
@adamwaite this still happens to me on the latest version and looking at the code in 3.1.1 the old style `textDidChangeNotification` notification names are still there...

**Comment by adamwaite** [comment]
Fixed in https://github.com/adamwaite/Validator/commit/4ef95eb33af5624647f9f0a4bf457916e0fabfca

**Comment by adamwaite** [comment]
(I think). This one is strange.
