### ISSUE TITLE
Verify All rules

### ISSUE THREAD

**Issue by rehannali** [adamwaite/Validator#111]
First of all, Thank you for such kind of Pod. It is very helpful.
Hi, I have form of different textfield and i've set all validation. Individually these are working fine. I need to check while submit while are field are valid or not. I read documentation but i didn't understand how can i do that?
You know some kind of check i.e. rule.allValid -> true or false (Something like that or anything else that can help to achieve the solution of this problem.

**Comment by adamwaite** [comment]
This is explained in the docs. Closing this because you're probably past this now :)
