### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by aodhol** [adamwaite/Validator#115]
Version: 3.1.1
Xcode: 10.1 (10B61)
macOS: 10.14

`'textDidChangeNotification' has been renamed to 'NSNotification.Name.UITextViewTextDidChange'` and

`'textDidChangeNotification' has been renamed to 'NSNotification.Name.UITextViewTextDidChange'`

The following code changes seems to fix the issue:

```swift
        switch enabled {
        case true: NotificationCenter.default.addObserver(self, selector: #selector(validate), name: NSNotification.Name.UITextViewTextDidChange, object: self)
        case false: NotificationCenter.default.removeObserver(self, name:
            NSNotification.Name.UITextViewTextDidChange, object: self)
        }
```

**Comment by adamwaite** [comment]
Fixed in https://github.com/adamwaite/Validator/commit/4ef95eb33af5624647f9f0a4bf457916e0fabfca
