### ISSUE TITLE
Xcode 11 & Swift 5.1 build failure

### ISSUE THREAD

**Issue by tevelee** [adamwaite/Validator#120]
![Screenshot 2019-06-05 at 13 36 58](https://user-images.githubusercontent.com/443078/58953602-46413200-8797-11e9-8074-546397f7dc09.png)
![Screenshot 2019-06-05 at 13 42 55](https://user-images.githubusercontent.com/443078/58953842-df704880-8797-11e9-8bc4-22a58cd9e4dc.png)
![Screenshot 2019-06-05 at 13 43 04](https://user-images.githubusercontent.com/443078/58953843-df704880-8797-11e9-8878-a021fe97ff5b.png)
![Screenshot 2019-06-05 at 13 37 09](https://user-images.githubusercontent.com/443078/58953603-46413200-8797-11e9-845d-9d57a42471ab.png)
7 build errors `Ambiguous use of validate` in the following 2 files:
- https://github.com/adamwaite/Validator/blob/master/Validator/Sources/UIKit+Validator/UISlider+Validator.swift#L41-L42
- https://github.com/adamwaite/Validator/blob/master/Validator/Sources/UIKit+Validator/UITextField+Validator.swift#L40-L48

**Comment by adamwaite** [comment]
Thanks, working on this now.

**Comment by adamwaite** [comment]
Fixed in https://github.com/adamwaite/Validator/commit/4ef95eb33af5624647f9f0a4bf457916e0fabfca
