### ISSUE TITLE
Missing return in a function expected to return 'Bool'

### ISSUE THREAD

**Issue by alexolivier** [adamwaite/Validator#122]
Upgraded to Swift 5 and build fails on `ValidationResult.swift` - `isValid` does not return a Bool

```
public enum ValidationResult {
    
    case valid
    
    case invalid([ValidationError])
    
    public var isValid: Bool {
        
        self == .valid
    }
}
```

**Comment by Lopdo** [comment]
Do you have plans to make a new release that will include this fix soon? Latest version still has this problem

**Comment by adamwaite** [comment]
Done 3.2.1

**Comment by Lopdo** [comment]
Thanks! I just noticed that part of the same commit that introduced this bug, `merge` methods on `ValidationResult` were removed. Was this intentional? if so, what is the right way of merging multiple results now?

**Comment by nrikiji** [comment]
> Thanks! I just noticed that part of the same commit that introduced this bug, `merge` methods on `ValidationResult` were removed. Was this intentional? if so, what is the right way of merging multiple results now?

Is this question solved?
