### ISSUE TITLE
How to make UITextView implement ValidatableInterfaceElement?

### ISSUE THREAD

**Issue by brcolow** [adamwaite/Validator#17]
Hello,

Great library! I have really enjoyed using it so far to validate UITextField's, it was painless. I was wondering how one could validate for a UITextView. After reading the readme, I came up with:

``` swift
extension UITextView: ValidatableInterfaceElement {

    public typealias InputType = String

    var inputValue: String { return text ?? "" }

    public func validateOnInputChange(validationEnabled: Bool) {
        switch validationEnabled {
        case true: addTarget(self, action: "validateInputChange:", forControlEvents: .EditingChanged)
        case false: removeTarget(self, action: "validateInputChange:", forControlEvents: .EditingChanged)
        }
    }

    @objc private func validateInputChange(sender: UITextView) {
        sender.validate()
    }

}
```

which is probably very wrong, because it is just a copy and paste, and the compiler gives these errors:

Type 'UITextView' does not conform to protocol 'ValidatableInterfaceElement'
Use of unresolved identifier addTarget
Use of unresolved identifier removeTarget

These errors make sense, because UITextView does not have addTarget/removeTarget methods. Sadly, my Swift-fu and Obj-C-fu are laughable, but it seems possible as in the following Stackoverflow question:

http://stackoverflow.com/questions/17497891/how-to-make-a-uitextview-call-the-addtarget-method

I tried making my UIViewController that has the UITextView implement UITextViewDelegate, and then:

``` swift
    func textViewDidChange(textView: UITextView) {
        keyText = textView.text
    }
```

but I am not sure how to wire this all up and make it work. Any ideas/suggestions? Also this could be an opportunity to add to the library, like UITextView+Validator.swift, as it would seem to be a pretty common thing, at least I would think so :).

Thanks very much.

**Comment by adamwaite** [comment]
Hey,

Glad you're liking the library.

`UITextView` is a little tricky because it doesn't inherit from `UIControl` so `addTarget` and similar are not in play. We could use the `delegate` property of the text view and validate in `UITextViewDelegate`'s change methods but I don't want to hijack that from users of the library. My first thought is to use [KVO](http://stackoverflow.com/questions/24092285/is-key-value-observation-kvo-available-in-swift) and validate when the text property changes somehow?

I'll try and get around to this some time this week. Meanwhile I suggest just validating from the view controller after it conforms to `UITextViewDelegate`.

Thanks!

**Comment by brcolow** [comment]
Thanks for your help - I will play with it and see if I can get it to work. I understand about you not wanting the library to hijack the UITextViewDelegate - that makes a lot of sense.

**Comment by adamwaite** [comment]
Great. I think there's something you can do to forward delegate methods through an `NSProxy` too, not sure if I just made that up though, will have a play soon.

**Comment by brcolow** [comment]
Just to report back, I was able to get it working by implementing UITextViewDelegate, and then implementing textViewDidChange thusly:

````swift
    func textViewDidChange(textView: UITextView) {
        let keyRule = ValidationRuleCondition<String>(failureError: ValidationError(message: "Invalid Key")) {
            $0?.rangeOfString("^[a-zA-Z0-9+\\/]+=$", options: .RegularExpressionSearch) != nil
        }

        let valid = textView.text.validate(rule: keyRule)
        switch valid {
        case .Valid:
            self.keyTextView.textColor = UIColor.blackColor()
            self.keyTextView.textColor = UIColor.greenColor()
            self.keyTextViewFeedback.text = "✓"
        case .Invalid(let failureErrors):
            let messages = failureErrors.map { $0.message }
            print(messages)
            self.keyTextView.textColor = UIColor.redColor()
            self.keyTextView.textColor = UIColor.redColor()
            self.keyTextViewFeedback.text = "✗"
        }
    }
````

Works like a charm =)

**Comment by adamwaite** [comment]
Good stuff, glad you got it working. I'm going to leave this open and try building it into the lib somehow when I find some spare time. Good luck with the rest of your project!

**Comment by ffittschen** [comment]
How about using the `NSNotificationCenter`?

```swift
extension UITextView: ValidatableInterfaceElement {
    
    public typealias InputType = String
    
    public var inputValue: String? { return text }
    
    public func validateOnInputChange(validationEnabled: Bool) {
        switch validationEnabled {
        case true: NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(UITextView.validateInput(_:)), name: UITextViewTextDidChangeNotification, object: self)
        case false: NSNotificationCenter.defaultCenter().removeObserver(self, name: UITextViewTextDidChangeNotification, object: self)
        }
    }
    
    public func validateOnEditingEnd(validationEnabled: Bool) {
        switch validationEnabled {
        case true: NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(UITextView.validateInput(_:)), name: UITextViewTextDidEndEditingNotification, object: self)
        case false: NSNotificationCenter.defaultCenter().removeObserver(self, name: UITextViewTextDidEndEditingNotification, object: self)
        }
    }
    
    @objc internal func validateInput(sender: NSNotification) {
        guard let sender = sender.object as? UITextView else {
            return
        }
        
        sender.validate()
    }
    
}
```

I'm just not sure how to remove the observers if the `UITextView`s are getting deinitialized...

**Comment by adamwaite** [comment]
@ffittschen Great idea. Had totally forgotten you could do that. When I need this functionality I'll build it in - if someone needs it in the meantime, feel free to give it a shot and submit a PR. As for observers, perhaps we could have a separate type that can never die that holds the actions and serves as the observer?

**Comment by dillidon** [comment]
I need it) please, add it)

**Comment by adamwaite** [comment]
UITextView is now a ValidatableInterfaceElement 🎉🎃
