### ISSUE TITLE
Error while trying to set via Carthage

### ISSUE THREAD

**Issue by txaidw** [adamwaite/Validator#22]
I`m getting this error when I add this repo in my Cartfile. like this:
github "adamwaite/Validator"
this is the error:

`Failed to discover shared schemes in project Example.xcodeproj — either the project does not have any shared schemes, or xcodebuild timed out.

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/adamwaite/Validator/issues/new`

What can I do?

**Comment by adamwaite** [comment]
Hi,

It was actually a pull request that added Carthage support. I've never used Carthage personally as I use CocoaPods instead.

Feel free to pull it and fix it.

Thanks

**Comment by adamwaite** [comment]
The warning should make enough sense though right? Just make the schemes shared in the workspace.

**Comment by txaidw** [comment]
I will try to make a PR then

**Comment by txaidw** [comment]
I was about to make a PR then i see that someone already fixed this, the only thing that is still missing to fix Carthage support is to release another version 1.1.1 with the fix from the latest commit. I think this issue can be closed when the new release is out!

Thanks!

**Comment by adamwaite** [comment]
[Done](https://github.com/adamwaite/Validator/releases/tag/v1.1.1)
