### ISSUE TITLE
Minimum deployment target iOS 9

### ISSUE THREAD

**Issue by MartijnSchoemaker** [adamwaite/Validator#24]
I added the module via Carthage. But I get this error:

Module file's minimum deployment target is ios9.0 v9.0: /Users/*/Carthage/Build/iOS/Validator.framework/Modules/Validator.swiftmodule/x86_64.swiftmodule

Isn't it possible to target on iOS 8?

**Comment by Shun-Nakahara** [comment]
Module file's minimum deployment target is ios9.0 v9.0: /Users/*/Carthage/Build/iOS/Validator.framework/Modules/Validator.swiftmodule/arm64.swiftmodule

I am similar.

**Comment by adamwaite** [comment]
Cool, make a pull request and i'll fix. I use CoacoaPods. Carthage has been added purely by contributors.

**Comment by adamwaite** [comment]
I'm sorry, I thought it was a Carthage thing stopping it from working for you. Thought the project was already iOS8. Fixed and merged.

**Comment by Shun-Nakahara** [comment]
Thank you ! :)
