### ISSUE TITLE
Revise ValidationPattern enum to handle Associated Values

### ISSUE THREAD

**Issue by ElliottFrench** [adamwaite/Validator#30]
Hi Adam, 

My team and I recently added a postcode validation pattern to Validator and have encountered the following issue when a validation pattern has a number of options. For example, UK postcodes can be provided lowercase, uppercase, with a space or without a space. Currently, we could provide a separate enum `case` for each according to the validation required, however, this quickly becomes unwieldy. 

An alternative is to restructure the `ValidationPattern` enum to handle associated values and return the appropriate regex as follows:

```
enum PostcodeOptions {
    case AllowsOptionalSpace
}

enum ValidationPattern {
    case EmailAddress
    case ContainsNumber
    case ContainsCapital
    case ContainsLowercase
    case UKPostcode(options: [PostcodeOptions])

    var pattern: String {
        switch self {
        case .EmailAddress:
            return "^[_A-Za-z0-9-+]+(\\.[_A-Za-z0-9-+]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z‌​]{2,})$"
        case .ContainsNumber:
            return ".*\\d.*"
        case .ContainsCapital:
            return "^.*?[A-Z].*?$"
        case .ContainsLowercase:
            return "^.*?[a-z].*?$"
        case .UKPostcode(let options):
            let optionalSpace = options.contains(.AllowsOptionalSpace) ? "[ ]?" : " "
            return "(GIR 0AA)|((([A-Z-[QVX]][0-9][0-9]?)|(([A-Z-[QVX]][A-Z-[IJZ]][0-9][0-9]?)|(([A-Z-[QVX]][0-9][A-HJKPSTUW])|([A-Z-[QVX]][A-Z-[IJZ]][0-9][ABEHMNPRVWXY]))))\(optionalSpace)[0-9][A-Z-[CIKMOV]]{2})"
        }
    }
}
```

You could also group the string patterns `.ContainsNumber`, `.ContainsCapital`, `.ContainsLowercase` into their own options group and construct the regex in a `.String` case creating one validation rule from multiple options.

I understand this proposal would change how users currently create validations and so wanted to first sound out your view on the value of this.

Many thanks

**Comment by adamwaite** [comment]
Hi Elliot, thanks for your contributions so far, great work! :dancer: 

I understand your point, it is indeed starting to get a little unwieldy.

I think a more flexible implementation might be to drop the `ValidationPattern enum` in favour of a protocol: `ValidationPattern`.

```
protocol ValidationPattern {
  var pattern: String { get }
}
```

Which can be used like this:

```
struct PostcodeValidationPattern: ValidationPattern {
  
   let thing: Thing?

   init(options: Blah) {
    //thing = options.thing...
  }

  var pattern: String {
      return // something that changes depending on thing
  }

}
```

That way we can capture much more logic, and have users define their own patterns for their own use cases without needing to pull request or fork etc. 

The library could potentially ship with many different user contributed `ValidationPattern`s - like your UKPostcode contribution. Each could be self contained, keeping it nice and clean.

How does that sound to you?

Afraid I'm mowed under with work right now, but if you're doing it anyway 😉

**Comment by racer1988** [comment]
Yes, +1 for this.

I need to define my company internal patterns and I have to create a separate ValidationRulePattern for each.

While doing a enum for the format would be better

**Comment by adamwaite** [comment]
Implemented in https://github.com/adamwaite/Validator/commit/c9f7b2ca4b0d8fb7f7950db28b75e62503546829

See https://github.com/adamwaite/Validator/blob/master/Validator/Validator/ValidationPattern.swift
