### ISSUE TITLE
check if specific field failed validation 

### ISSUE THREAD

**Issue by kiwo12345** [adamwaite/Validator#31]
Is there any way to check if a specific field has failed the validation?
I have a UIView under each textfield, and I want to color the UIView red under the textfield that fails validation.

And big thanks for sharing this lib!

**Comment by adamwaite** [comment]
textfield.superview?.backgroundColor = UIColor.redColor() perhaps?

**Comment by adamwaite** [comment]
I'm closing this because it's kind of more related to your app than the lib.

**Comment by kiwo12345** [comment]
@adamwaite 
I explained myself bad, under each textfield I have a UIView styled as a line, in order to have a "bottom border" for each textfield. So now I need to check if a specific textfield failed validation.

So is there anyway to check if "textFieldOne" has failed the validation?

**Comment by adamwaite** [comment]
You read the README?
