### ISSUE TITLE
Empty Validation Rule

### ISSUE THREAD

**Issue by pbassut** [adamwaite/Validator#32]
I guess such a validation rule is pretty common.
Although this could be as simple as ```ValidationRuleLength(min: 1, failureError: error)``` having a shortcut method for it would be awesome. 
Useful and fast enhancement

**Comment by adamwaite** [comment]
Check out `ValidationRuleRequired`

https://github.com/adamwaite/Validator/blob/master/Validator/Validator/Rules/ValidationRuleRequired.swift

See the readme for usage.

Ty

**Comment by pbassut** [comment]
I've tried that. And no, it doesn't solve my problem because when using UITextFields, they always have at least an empty string. 
That validator checks against ```nil```. Thus, it will always be valid.

**Comment by adamwaite** [comment]
Extend the library as you like. Maybe:

```
extension Validator {

  static var err = SomeError()

  static var blankRule: ValidationRuleLength {
    ValidationRuleLength(min: 1, failureError: err)
  }
}
```

I think creating this sort of convenience method litters the convention so i don't really want to put it in.

**Comment by pbassut** [comment]
Yea, I already did that.
My main point was that if it's a drop-in validation library, it should cover a fair amount of use cases.

But cool, sure.
