### ISSUE TITLE
Validate on input change blows up for UITextField subclasses

### ISSUE THREAD

**Issue by tomaskraina** [adamwaite/Validator#33]
Validate on input change blows up for UITextField subclasses [on this line](https://github.com/adamwaite/Validator/blob/1055fbb99075d799bb99813653436df6625f327b/Validator/Validator/UIKit%2BValidator/ValidatableInterfaceElement.swift#L74) with the following message:

```
Could not cast value of type 'Validator.(Box in _8483EA982F7B609A32A9F5BE7106930E)<(Validator.ValidationResult, MyApp.MyTextField) -> ()>' (0x1257e01b0) to 'Validator.(Box in _8483EA982F7B609A32A9F5BE7106930E)<(Validator.ValidationResult, UITextField) -> ()>' (0x1257e0330).
```

I came up with a workaround by overriding methods and properties declared by `ValidatableInterfaceElement` in my `MyTextField`, but it would be nice if I didn't need to do that :)

```swift
extension MyTextField {
    
    typealias InputType = String
    
    override var inputValue: String { return text ?? "" }
    
    override func validateOnInputChange(validationEnabled: Bool) {
        switch validationEnabled {
        case true: addTarget(self, action: "validateInputChange:", forControlEvents: .EditingChanged)
        case false: removeTarget(self, action: "validateInputChange:", forControlEvents: .EditingChanged)
        }
    }
    
    @objc private func validateInputChange(sender: MyTextField) {
        sender.validate()
    }
    
}
```

Any ideas on how to approach this issue?

**Comment by zjTek** [comment]
i met this error too

**Comment by guveniscan** [comment]
i have the same issue, thanks for the workaround @tomaskraina

**Comment by adamwaite** [comment]
Seems a few are seeing this so will look into it when I get chance

**Comment by animeshp** [comment]
I also faced this issue. Using @tomaskraina's solution for workaround.

**Comment by slxl** [comment]
for me even workaround didnt work. MyCustomTextField inherits from _AnotherCustomTextField_ located in another module (_ACTF_ is from CocoaPods)

**Comment by Appsido** [comment]
Same here if we try to use validator on UITextField subclass it do not work. Any workaround so far ?

**Comment by jedmund** [comment]
Also using @tomaskraina's workaround. Definitely should be fixed in the actual repo.

**Comment by adamwaite** [comment]
I'm ridiculously busy of late. The pull request button is there for anyone that wants to fix it.

**Comment by adamwaite** [comment]
Sorted. validationHandler now takes the form `ValidationResult -> ()` rather than `ValidationResult, Self -> ()` because it was impossible to cast in the `Box` unwrapping in the getter of the associated object validation handler closure as far as I could tell. It's a breaking change but easy to handle.
