### ISSUE TITLE
Swift 3 deprecations fix in release

### ISSUE THREAD

**Issue by balazsgerlei** [adamwaite/Validator#35]
Hi!
The currently released version still has deprecation warnings in it because of things like associatedtype and new selector syntax. I've seen that there is a commit in master that fixes it, but I would like to ask when will it be available via a release? It is not too good to point to the master branch in a production code.

Thank you!

**Comment by adamwaite** [comment]
Thanks, Released 1.1.2 on CocoaPods.

**Comment by balazsgerlei** [comment]
Nice, thank you!
