### ISSUE TITLE
Mobile regex

### ISSUE THREAD

**Issue by dillidon** [adamwaite/Validator#39]
Could you add good regex pattern for international mobile as well as UIextField, which automatically format phone humber (like PhoneNumberKit)?

**Comment by adamwaite** [comment]
I'll get to this with https://github.com/adamwaite/Validator/issues/30 as soon as I can.

**Comment by adamwaite** [comment]
https://github.com/adamwaite/Validator/issues/30 makes it easy to create your own. Closing this since it's so old and nobody else is asking for it. If there's a higher demand I'll re-open.
