### ISSUE TITLE
Correct way to validate on submit

### ISSUE THREAD

**Issue by StuartMorris0** [adamwaite/Validator#40]
Hello,

It appears that all validation is completed inline. Is there a way to double confirm validation on submit of a form for example.

I want to either check the current validation status or revalid against the same rule again to confirm. Otherwise when a submit button is pressed there might be multiple rows still in a bad state.

Thanks

**Comment by adamwaite** [comment]
You can validate directly.

```
@IBAction func submit(sender: AnyObject?) {
  let result = textfield.text.validate(rules: textFieldRules)
  if result.isValid {
    // ...
  }
}
```

Should be pretty clear in the read me.

Thanks
