### ISSUE TITLE
Should validate() have @discardableResult in Swift 3.0?

### ISSUE THREAD

**Issue by jedmund** [adamwaite/Validator#43]
I'm getting a lot of `Result of call to 'validate()' is unused` warnings.

This could just be how I've implemented Validator in my app, but if not, we should add `@discardableResult` to the validate function to silence these warnings. I'm happy to make the changes if others think this is the right way to go.

**Comment by adamwaite** [comment]
Ahhhh, hadn't event seen `@discardableResult`. I'll implement this and let you know to double check what you think. Currently merging everything into the swift-3 branch from yours.

**Comment by adamwaite** [comment]
That's it, **thanks** for all of your hard work.  

Everything's good to go on the https://github.com/adamwaite/Validator/tree/swift-3 branch.

Really saved me a massive job! 🍺

**Comment by adamwaite** [comment]
You're the first member in the new thanks section of the README, and in a note at the top of the master branch.

**Comment by jedmund** [comment]
Thanks a bunch! Really appreciate it. I'll try to keep helping out where I can.
