### ISSUE TITLE
Numbers only

### ISSUE THREAD

**Issue by StuartMorris0** [adamwaite/Validator#44]
Is there a way to make a validation rule for numbers only? I see contains digits, but looking to have a textfield that can only accept numbers.

Thanks

**Comment by racer1988** [comment]
You can make your own validationRulePattern with a regex

    [0-9]* 

that should be good for you

**Comment by adamwaite** [comment]
Thanks @racer1988.

You can also do something like this:

```
public struct NumbericValidationPattern: ValidationPattern {
    
    public var pattern: String {
        return "[0-9]*"
    }
}

let rule = ValidationRulePattern(pattern: NumbericValidationPattern(), error: someError)
```
