### ISSUE TITLE
ValidationRuleSet not working with Required rule

### ISSUE THREAD

**Issue by sneps85** [adamwaite/Validator#49]
when i have a validationrulest<string> and add a required rule<string> and others (e.g. email), then only email is validated, the required rule is ignored.

i think it is because string cannot be nil... why dont you check for empty string if type is string in the required rule?

**Comment by cody1024d** [comment]
I think this mainly occurs when the textfield validates itself.  When it triggers the ValidationRuleRequired, the text that is passed in is actually an empty string.

**Comment by adamwaite** [comment]
That's it Cody. This is perhaps poor implementation on my part. Will look out if any more people trip up on this and reconsider if yes.

**Comment by cody1024d** [comment]
@adamwaite In the interim, I've gotten around it with using a length validation rule (if anyone else asks this same question and needs a work-around).  Also, perhaps so you don't break backwards compatibility, you could just add a flag to the constructor, or something, a bit hacky, but at least it would be a bit of a "safer" change then.
