### ISSUE TITLE
ValidationErrorType Priority

### ISSUE THREAD

**Issue by maarek** [adamwaite/Validator#50]
What is the best way to handle Error priority so that when multiple rules are hit, we can easily identify the priority of the rules? The point of validation does not know priority of the validation in a ValidationRuleSet.

**Comment by racer1988** [comment]
In my tests, the validation rules in a set are triggered in the order you added them.
So add the rules with more priority first to your set.

can you try and see if that works?

**Comment by adamwaite** [comment]
That's right, the rules are evaluated in the order added. Cheers.
