### ISSUE TITLE
ValidationRuleSet.init(rules: [AnyValidationRule])

### ISSUE THREAD

**Issue by maarek** [adamwaite/Validator#51]
With the use of Self in the ValidationRuleSet struct, we cannot mix rules in the current inits when one rule has an associated type and others do not. Should there be an init method so we can pass in the type erasure form of the rule and open up the possibly of passing [AnyValidationRule] instead of having to .add() for each and every rule?

**Comment by adamwaite** [comment]
Will look into this tonight

**Comment by adamwaite** [comment]
By 'tonight' I meant someday

**Comment by adamwaite** [comment]
This is as far as I think we need to take this one. https://github.com/adamwaite/Validator/pull/37/commits/5e003d0c3ab78b7a606dc31805188e72836fd8bc
