### ISSUE TITLE
ValidationRuleLength on Nil

### ISSUE THREAD

**Issue by maarek** [adamwaite/Validator#53]
This rule will always trigger when String? is nil. If the string is nil and min >= 0 then this should probably treat the nil string as an empty string.

> input?.characters.count >= min
> false

**Comment by adamwaite** [comment]
Thanks! Will sort this soon

**Comment by adamwaite** [comment]
Hang on, sorry I'm not sure I understand you.

Should handle nil as being invalid anyway.
```
public func validate(input: String?) -> Bool {
        guard let input = input else { return false }
        return input.characters.count >= min && input.characters.count <= max
    }
```

**Comment by piv199** [comment]
@adamwaite nil should be handled as 0
