### ISSUE TITLE
No Documentation for any method

### ISSUE THREAD

**Issue by racer1988** [adamwaite/Validator#55]
Hello!

I just started using this framework, which is very cool and flexible 👍 

I wanted to raise a point.
There is no documentation on any method/class in this project.

This is very cumbersome because it forces me (or any new user) to read the entire source code to understand why there is a specific parameter, or what are the other methods that are not documented in the README etc..

For example I had to look for `validateOnEditingEnd` which is exactly what I need, but I had to check the source code to be sure,
while some documentation would let me do the same thing from my editor, which is the purpose of using a framework instead of writing myself the whole code

just my 2cents

**Comment by adamwaite** [comment]
Hey, thanks for the feedback, I'll be looking to add some documentation soon!

**Comment by racer1988** [comment]
I am quite busy in this period so I had not have the time to contribute.
Just opened the issue to explain what I think would be a valuable improvement to the use of the framework ;)

**Comment by adamwaite** [comment]
It's all documented now. Example: https://github.com/adamwaite/Validator/blob/master/Validator/Validator/Validatable.swift
