### ISSUE TITLE
Protocol 'ValidatableInterfaceElement' can only be used as a generic constraint because it has Self or associated type requirements

### ISSUE THREAD

**Issue by racer1988** [adamwaite/Validator#56]
Protocol 'ValidatableInterfaceElement' can only be used as a generic constraint because it has Self or associated type requirements.

So I cannot check if a element is a ValidatableInterfaceElement and has a validate method on it?

**Comment by adamwaite** [comment]
Are you trying to enumerate over a collection of `ValidatableInterfaceElement`s? You can't yet store an array of types conforming to a protocol if they have associated type requirements (in this case, the validated type). To do this we'd need to erase the type using something like what I have done for `ValidationRule` and `AnyValidationRule`. I'll have a look if this is worth implementing.

**Comment by racer1988** [comment]
Thanks,

yea, after posting the issue I started reading about Type Erasure.
Which is pretty messy ehehe 😮 

I don't know if it is important for this framework, but let's say I use a array to keep track of all my Form Elements in a controller.
When a Submit is done, I want to be able to disable all the elements, textfields, buttons etc.. in order to avoid any further user interaction and validate them, however I cannot check if the element is of type ValidatableInterfaceElement because of the generic typealias.

I don't know if it would be interesting for the framework to provide a wrapper class which erase the type for ValidatableInterfaceElement in order to do comparison on UI elements 
or
if this is a specific case and should be left to the end user to do the type erasure.

**Comment by adamwaite** [comment]
Ah ok. Yeah I don't think I'd want to expose any type-erased types to the consumer of the API to keep things easy. `AnyValidationRule` is meant to be hidden away from people and just used behind the scenes. I think the user should do the type erasure in this case. Thanks for the input!
