### ISSUE TITLE
Require Function

### ISSUE THREAD

**Issue by AdventuresOfMar** [adamwaite/Validator#57]
Hello All,

I have a really quick question, is there an example for using the require function? I've tried implementing and once I use 

 let stringRequiredRule = ValidationRuleRequired<String?>(failureError: ValidationError(message: "😫")) 

 stringCell.validationRuleSet?.add(rule: stringRequiredRule)

I get the following error 
Generic parameter 'R' could not be inferred

**Comment by maarek** [comment]
Validations here are sometimes type specific using associated types. See the following on how to fix your issue. 

```
var ruleSet: ValidationRuleSet = ValidationRuleSet<String>()
ruleSet.addRule(ValidationRuleRequired<String>(failureError: ValidationError(message: "😫")))
```

**Comment by iHunterX** [comment]
This not working, i cant apply the required rule for the textfield 
it wont show the error of required rule

**Comment by adamwaite** [comment]
Can you be more specific?

**Comment by iHunterX** [comment]
self.validationRuleSetUserName?.add(rule: ValidationRuleRequired<String>(failureError: ValidationError(message: "😫")))

I used this but it wont show message when im not adding text and validate the textfield, thanks for you help

**Comment by adamwaite** [comment]
Ah ok. I got you. It's because UITextField returns a blank string to validate, which is non-nil. You should use a ValidationRuleLength and make sure it's above 0
