### ISSUE TITLE
Api misalignement

### ISSUE THREAD

**Issue by racer1988** [adamwaite/Validator#61]
Shall the API align to both say enabled? 
This was changed in https://github.com/adamwaite/Validator/blob/47d675b9a864f6aff91c3c45e3256147896d0556/Validator/Validator/UIKit%2BValidator/UITextField%2BValidator.swift

    open func validateOnInputChange(enabled: Bool) {
    open func validateOnEditingEnd(validationEnabled: Bool) {

**Comment by adamwaite** [comment]
Ah yeah. I need to change.

**Comment by racer1988** [comment]
problem with those API changes is that they are non backward compatible.
I had to change my code to keep it working, so maybe it would be best to sum up all those API changes together and then do a major version release

**Comment by adamwaite** [comment]
Fixed
