### ISSUE TITLE
ValidationDateRangeRule

### ISSUE THREAD

**Issue by AdventuresOfMar** [adamwaite/Validator#62]
Greetings again, one final question, I noticed that in the pull requests there use to exist a Date Range validation rule. Was this ever merged into the main library?

**Comment by adamwaite** [comment]
Since `Date` is actually a `Comparable` type in Swift, we can use `ValidationRuleComparison<Date>`. Hope that helps you!

**Comment by adamwaite** [comment]
Added note in README

**Comment by AdventuresOfMar** [comment]
HI @adamwaite, thanks so much for the update!
I''m still a bit confused, I took a look at your example and tried implementing your logic as follows;
 let pickerCell = tableView.dequeueReusableCell(withIdentifier: "pickerCell", for: indexPath as IndexPath) as! PickerCell
            
            cell = pickerCell
            pickerCell.validationRuleSet = ValidationRuleSet<String>()
            let eighteenYearsAgo = Date().addingTimeInterval(-568024668)
           
            let dateOfBirth = Date().addingTimeInterval(-662695446) // 21 years old
            let drinkingAgeRule = ValidationRuleComparison<Date>(min: eighteenYearsAgo, max: dateOfBirth , failureError: ValidationError(message: "Must be atleast 18 to use"))
           pickerCell.validationRuleSet?.add(rule: drinkingAgeRule) 

The error that's outputting is "Generic parameter 'R' could not be inferred", I'm sure i'm just not using the function correctly and will continue to play around and see what I can do but if you have any suggestions I'd really appreciate it

**Comment by adamwaite** [comment]
You're trouble here is that you're using a `ValidationRuleSet<String>` to validate a `Date`. You'll need a `ValidationRuleSet<Date>` to validate a `Date` type. Hope that helps?
