### ISSUE TITLE
Why differentiate between ValidationRule and ValidationRuleSet?

### ISSUE THREAD

**Issue by maguro** [adamwaite/Validator#65]
This is an **_awesome_** project.  A real treasure trove of Swift patterns for us newbies.  I feel odd filing an issue for a general question.  Maybe it would be a good idea to start up a Google Group, or something of that ilk?

Why differentiate between `ValidationRule` and `ValidationRuleSet`?  I would have thought that `ValidationRuleSet` would inherit from `ValidationRule`.  I'm sure that I'm missing some overriding pattern.  TIA

**Comment by adamwaite** [comment]
Hi. Glad you like the library. I actually wrote it when I was learning how to write in Swift too. A general question in GitHub is fine. 

So the difference between `ValidationRule` and `ValidationRuleSet` is that the set version is a collection of `ValidationRule`s. You get me? So a `ValidationRuleSet` is just a container to store multiple `ValidationRule`s. e.g. an email address field might be required and require a valid email, so you'd create a `ValidationRuleSet` containing the two rules.

**Comment by maguro** [comment]
Yes, I think I understand that `ValidationRuleSet` is a set of `ValidationRule`s, but why not have `ValidationRuleSet` implement `ValidationRule`? 

All the `UITextField` instance cares about is if it's valid or not.   From the perspective of a `UITextField`, it shouldn't care if the validator is a set or a single rule; such information seems like an implementation leak.

**Comment by adamwaite** [comment]
The main reason is that we want multiple errors should multiple rules fail.

**Comment by maguro** [comment]
Why not have `ValidationRules.validate` return a set?  Then integrations won't need to handle two code paths.

**Comment by maguro** [comment]
Here's an example of where things seem to be a bit asymmetric.  In `ValidatableInterfaceElement`
```
    @discardableResult public func validate(editingDidEnd: Bool) -> ValidationResult {
        guard let attachedRules = validationRules else { fatalError("Validator Error: attempted to validate without attaching rules") }
        return validate(rules: attachedRules)
    }
```

**Comment by adamwaite** [comment]
Feel free to create a pull request with your improvements. Thanks.
