### ISSUE TITLE
Need different validators for .editingChanged and .editingDidEnd

### ISSUE THREAD

**Issue by maguro** [adamwaite/Validator#66]
It seems that I can only register one validator.  Is the thinking that I register my own custom target/action if I need such customization?

**Comment by adamwaite** [comment]
Oh I'd never thought of that use case! It's not something I want to build into the library right now. I recommend creating your own target actions, yes.

**Comment by maguro** [comment]
No worries.  May I ask why it's not something you want to build into the library right now?  Would you mind if I submitted a PR?

Performing validation at the _end_ of editing is quite common, e.g. ensuring a user name is unique.

**Comment by adamwaite** [comment]
Please feel free
