### ISSUE TITLE
Sent Events section disappeared from Connections Inspector/Menu

### ISSUE THREAD

**Issue by maguro** [adamwaite/Validator#67]
When I add **Validator** to my project, the "Sent Events" section disappears from my Storyboard's Connections Inspector/Menu.  I'm a bit of a GUI weenie so I was alarmed at first.  I know that I can hand code Target/Action connections, so I calmed down after a while.  But still, I'd still like to mix both Validator and Storyboard managed Target/Action connections.

Is that possible?

Why did the the "Sent Events" section disappear?  I sense an opportunity to learn about the deeper workings of Storyboard, hand registration of target/actions for particular events.

**Comment by adamwaite** [comment]
Hey there. Validator shouldn't affect this. Are you sure you added `@IBAction` to the `func` declaration?

**Comment by maguro** [comment]
This is before an `@IBAction` is added to a `func` declaration.

## before:
<img width="1440" alt="screen shot before" src="https://cloud.githubusercontent.com/assets/165060/20644266/c0bab9be-b3e3-11e6-937a-6d589845dc86.png">

## after
<img width="1440" alt="screen shot after" src="https://cloud.githubusercontent.com/assets/165060/20644267/c1e4b556-b3e3-11e6-8f9f-8b191a8d9e8d.png">

**Comment by piv199** [comment]
@adamwaite Hi, yes, this is an error caused by extending any native Apple element.

This is caused by `extension UITextField: ValidatableInterfaceElement`. But this is really a bug from Apple!

[Apple forum link](https://forums.developer.apple.com/message/84535#84535)
