### ISSUE TITLE
FatalError when no attached rules

### ISSUE THREAD

**Issue by piv199** [adamwaite/Validator#68]
Is this a really good behaviour?

I have an array of text fields for UIViewController and I iterate over all and run `validate()` and merging the result of the validation... But if there is no attached rules fatal error is thrown...

Personally, I would suggest returning `.valid` if there is no rules attached to `ValidatableInterfaceElement` instead of throwing fatal error. What do you think guys?

**Comment by adamwaite** [comment]
Perhaps. I think at the time of writing I considered it a programmer error to validate a field that hasn't any attached validators. You're probably right, `.valid` is probably a better bet. Perhaps a print message in `DEBUG` mode?
