### ISSUE TITLE
 Example for Required rule is not correct

### ISSUE THREAD

**Issue by DzonyKalafut** [adamwaite/Validator#70]
In README you have 

```
let stringRequiredRule = ValidationRuleRequired<String?>(error: someValidationErrorType)

let floatRequiredRule = ValidationRuleRequired<Float?>(error: someValidationErrorType)
```

If you specify you rule type as optional, you will get double optionals inside validate method and it will always evaluate input as valid, making the rule useless. (Input to validate method is already specified as Optional of generic type, so for String? type you will then get String?? inside the method)

**Comment by RogerBCA** [comment]
Export this file to your project and should work

https://github.com/adamwaite/Validator/blob/master/Example/Example/ValidationErrorType.swift

**Comment by AgapovOne** [comment]
@DzonyKalafut is right. Your example is incorrect. You should specify non-optional generic for `ValdiationRuleRequired`. Otherwise it won't work. 
Please, fix README with these lines:
```
let stringRequiredRule = ValidationRuleRequired<String>(error: someValidationErrorType)
let floatRequiredRule = ValidationRuleRequired<Float>(error: someValidationErrorType)
```
