### ISSUE TITLE
How to use custom rule in swift 3.0

### ISSUE THREAD

**Issue by vandanakanwar** [adamwaite/Validator#75]
Hi @adamwaite ,
I am using Validator in my project.
Can you please help me in using custom rule in swift 3.0
Please check below code: 

```
internal struct WhitespaceRule {
    typealias InputType = String
    var error: ValidationError = ValidationError(message: "")
    init(message: String?) {
        self.error = ValidationError(message: message ?? "Please enter valid character")
    }
    func validate(input: String?) -> Bool {
        guard let nameText = input else { return false }
        let trimmedString = nameText.trimmingCharacters(in: CharacterSet.whitespaces)
        return !trimmedString.isEmpty
        return true
    }
}
```

But when I use this rule in my class like
```
nameRules.add(rule: WhitespaceRule(message: "Please enter an item name"))
```
It is giving me error argument type 'WhitespaceRule' does not conform to expected type 'ValidationRule'

}

**Comment by adamwaite** [comment]
You should make `WhitespaceRule` conform to `ValidationRule`, like this:

`internal struct WhitespaceRule: ValidationRule {`

**Comment by croossin** [comment]
I am seeing an issue where I am conforming to `ValidationRule`, yet it still throws an error saying that the custom rule does not conform to expected type....

```
struct AgeRule: ValidationRule {

    typealias InputType = String
    var error: Error = ValidationError.atleast13
    func validate(input: String?) -> Bool {
        
        guard let date = input, let dob = date.toDate(date: .signup) else { return false }
        
        let thirteenYearsAgo = Date().addingTimeInterval(-410240038)
        
        return dob > thirteenYearsAgo
    }
}
```

Any help is appreciated!

**Comment by kiokumicu** [comment]
@croossin
Got the same error (
Any solution ?

**Comment by croossin** [comment]
@kiokumicu Haven't checked recently... but when I was using it I was unable to find a solution unfortunately.

**Comment by adamwaite** [comment]
Hi @kiokumicu and @croossin.

I tried with this:

```
enum ValidationError: Error {
    case atleast13
}

struct AgeRule: ValidationRule {
    
    typealias InputType = String
    var error: Error = ValidationError.atleast13
    func validate(input: String?) -> Bool {
        
        guard let date = input else {
            return false
        }
        
        let dob = Date()
        
        let thirteenYearsAgo = Date().addingTimeInterval(-410240038)
        
        return dob > thirteenYearsAgo
    }
}
```

And it compiles fine.

Are you using the latest version?

**Comment by kiokumicu** [comment]
Hi @adamwaite 
I'm using 2.1.1 version.
I have error when I'n trying use this rule

```
Validator.validate(input: personBirth, rule: AgeRule)
```
`Cannot invoke 'validate' with an argument list of type '(input: String, rule: AgeRule.Type)'`
