### ISSUE TITLE
Submit new cocoapods version with warnings fixed

### ISSUE THREAD

**Issue by dfischbach** [adamwaite/Validator#87]
Could you please publish a new cocoapods version 3.0.1 with your latest fix, which removes the warnings for .characters? The 3.0.0 version has the warnings in. Actually a git reference to master is needed  to get rid of the warnings.

**Comment by adamwaite** [comment]
<img width="1090" alt="screen shot 2018-02-14 at 17 56 50" src="https://user-images.githubusercontent.com/1426233/36219804-778c15f4-11b0-11e8-8d44-3f558f6d2ad2.png">

Job done.
