### ISSUE TITLE
How to validate Textfield value is equal to another Textfield's value?

### ISSUE THREAD

**Issue by jlstr** [adamwaite/Validator#89]
Hello adam!

May I ask real quickly here, what's the simplest way to Perform the classic Validation of one field's value being equal to another field's value? This, in order to implement the classic "Confirm Password" functionality.

Is this easily done with you Library?
Thanks in advance!

**Comment by adamwaite** [comment]
Have a look at the dynamic rule in the README

**Comment by jlstr** [comment]
Thanks Adam, I was able to figure it out some time ago, should have closed this one myself. Thank you once more
