### ISSUE TITLE
Issue in Email Validation

### ISSUE THREAD

**Issue by kareemDev** [adamwaite/Validator#90]
Issue in email validation, I've "intered skskkd@ssldd..." , if it's more than 1 dot, it's passing the validation.

Thanks for the amazing pod.

![simulator screen shot - iphone 8 plus - 2018-03-01 at 11 20 56](https://user-images.githubusercontent.com/30798464/36834055-9ebaeb80-1d42-11e8-826a-4aebf518467a.png)

**Comment by shoaibahmedqureshi** [comment]
Is it still a valid issue ? I would like to help in fixing if it is.

**Comment by shoaibahmedqureshi** [comment]
I looked into this issue and it is because of the simple format given in the library. Standard format pretty much covers all email addresses and I am not sure the reason for keeping the simple format. Can anyone further guide me through it ?

**Comment by adamwaite** [comment]
Thanks
