### ISSUE TITLE
poor example

### ISSUE THREAD

**Issue by Nathan187** [adamwaite/Validator#97]
trying to figure out how this works.  not every app uses table views.  a better example would have been nice

**Comment by adamwaite** [comment]
Thanks for the feedback. Please feel free to make a pull request with a better example.

**Comment by Nathan187** [comment]
no need.  i suffer from RTFM (or not)

**Comment by shayneoneill** [comment]
Some indication of what the "validationError" thats passed to the constructor is supposed to be would be welcome though.
