### ISSUE TITLE
UItextview, Uitextfield, UiSlide do not conform to ValidatableInterfaceelement

### ISSUE THREAD

**Issue by serge-glance** [adamwaite/Validator#98]
I just upgraded to xcode 9.3.

Am getting non conformance to ValidatableInterfacElement protocol
specifically the method:
public func validate<R: ValidationRule>(rule r: R) -> ValidationResult where R.InputType == InputType {
        let result = Validator.validate(input: inputValue, rule: r)
        if let h = validationHandler { h(result) }
        return result
    }

i copied and pasted it into the UITextView,UISlider,UITextfield extensions and it will go away.

Is this because you have an extension in an extension?

Should just compile no problems from pods but it does not.

**Comment by adamwaite** [comment]
See https://github.com/adamwaite/Validator/issues/93
