### ISSUE TITLE
Anyway to pass custom error based on specific condition?

### ISSUE THREAD

**Issue by Tayyab-VenD** [adamwaite/Validator#99]
The `ValidationRuleCondition` accepts a block to evaluate a custom condition. But is there anyway to pass custom error based on a specific condition. I know there is `ValidationRuleSet` to validate multiple inputs. But my specific use case requires me to return custom errors based on specific conditions. Is there an elegant solution to do this?

**Comment by adamwaite** [comment]
`ValidationRuleSet` containing multiple `ValidationRuleCondition`s is the way to go for this use case.

**Comment by Tayyab-VenD** [comment]
Just to clarify my requirement, I needed to check whether the entered value is an email or phone number. Both rules had different error messages. If email is validated, phone number rule should not be checked. Similarly if phone number is validated, email rule should not be checked. So as you suggested, I used multiple `ValidationRuleCondition` but with their `OR`ing. Following is the extension I used.

```swift
extension ValidationRule {
    func or<R>(_ otherRule: R) -> ValidationRuleCondition<R.InputType> where R: ValidationRule, R.InputType == InputType {
        return orAnyOf(otherRule)
    }

    func orAnyOf<R>(_ otherRules: R...) -> ValidationRuleCondition<R.InputType> where R: ValidationRule, R.InputType == InputType {
        return ValidationRuleCondition<InputType>(error: error) { (input) -> Bool in
            if self.validate(input: input) {
                return true
            }

            for other in otherRules {
                if other.validate(input: input) {
                    return true
                }
            }

            return  false
        }
    }
}
```

And the rules became
```swift
var rules = ValidationRuleSet<String>()
rules.add(rule: emailRule.or(mobileRule))
rules.add(rule: mobileRule.or(emailRule))
```

**Comment by adamwaite** [comment]
Oh! I didn't understand your use-case! This is very interesting and I like your implementation.

I'm going to re-open this to considered in the next version, which I hope to start soon.

Thank you!

**Comment by Tayyab-VenD** [comment]
Glad to hear that :)

And I would like to raise one more use case. Its the localization that needs to be handled. If the language of an app is changed at runtime, there should be a way to update the localization of error message.

It would be great to have examples of these use cases in the readme.

**Comment by adamwaite** [comment]
Hi, the next version (3.2) addresses the localization by introducing ValidationError. I have decided to leave out the `or` for now though.
